CREATE TABLE IF NOT EXISTS memories (
  id TEXT PRIMARY KEY,
  text TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tasks (
  id TEXT PRIMARY KEY,
  customer_name TEXT NOT NULL,
  work_goal TEXT NOT NULL,
  source_memory TEXT NOT NULL DEFAULT '',
  deadline TIMESTAMPTZ NOT NULL,
  daily_time TEXT NOT NULL,
  priority TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS manual_alerts (
  id TEXT PRIMARY KEY,
  message TEXT NOT NULL,
  alert_at TIMESTAMPTZ NOT NULL,
  fired BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS fired_alerts (
  key TEXT PRIMARY KEY,
  fired_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
